name: Start Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start server
        run: |
          export PORT=5000
          python tts_server.py &
          PID=$!
          sleep 15
          curl -I http://127.0.0.1:$PORT/tts?text=hello
          kill $PID
